name: ai_health_coach
description: "AI Health Coach mobile app for adaptive rehab workouts."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.3.4
  firebase_analytics: ^11.5.0
  firebase_crashlytics: ^4.3.10
  
  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.0.3
  
  # Navigation
  go_router: ^14.6.2
  
  # Environment Variables
  flutter_dotenv: ^5.2.1
  
  # AI Integration
  google_generative_ai: ^0.4.6
  
  # Utils
  intl: ^0.20.0
  google_fonts: ^8.0.1
  shared_preferences: ^2.5.4
  http: ^1.6.0
  fl_chart: ^1.1.1
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  youtube_player_iframe: ^5.2.2
  video_player: ^2.10.1
  chewie: ^1.13.0
  webview_flutter: ^4.13.0
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/ai_health_coach_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/ai_health_coach_logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/ai_health_coach_logo.png
